- hosts:
  - kube-node
  - deploy
  tasks:
  - name: stop kube-node service
    shell: "systemctl stop kubelet kube-proxy docker"
    ignore_errors: true

  - name: umount kubelet 挂载的目录
    shell: "mount | grep '/var/lib/kubelet'| awk '{print $3}'|xargs umount"
    ignore_errors: true

  - name: 清理目录和文件
    file: name={{ item }} state=absent
    with_items:
    - "/var/lib/kubelet/"
    - "/var/lib/docker/"
    - "/var/run/docker/"
    - "/etc/kubernetes/"
    - "/etc/systemd/system/kubelet.service"
    - "/etc/systemd/system/docker.service"
    - "/etc/systemd/system/docker.service.requires/"
   # - "/root/local/bin/"

  - name: 清理 iptables
    shell: iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat

- hosts: kube-master
  tasks:
  - name: stop kube-master service
    shell: "systemctl stop kube-apiserver kube-controller-manager kube-scheduler"
    ignore_errors: true

  - name: 清理目录和文件
    file: name={{ item }} state=absent
    with_items:
    - "/var/run/kubernetes"
    - "/etc/systemd/system/kube-apiserver.service" 
    - "/etc/systemd/system/kube-controller-manager.service" 
    - "/etc/systemd/system/kube-scheduler.service"
    - "/etc/kubernetes/"

- hosts:
  - kube-cluster
  - deploy
  tasks:
  - name: stop flannel service
    shell: "systemctl stop flanneld"
    ignore_errors: true

  - name: 清理网络
    shell: "ip link del docker0; systemctl restart networking; ip link del flannel.1"
    ignore_errors: true

  - name: 清理目录和文件
    file: name={{ item }} state=absent
    with_items:
    - "/var/run/flannel/"
    - "/etc/systemd/system/flanneld.service"
    - "/root/.kube/"

- hosts: etcd 
  tasks:
  - name: stop etcd service
    shell: systemctl stop etcd
    ignore_errors: true

  - name: 清理目录和文件
    file: name={{ item }} state=absent
    with_items:
    - "/var/lib/etcd"
    - "/etc/etcd/"
    - "/etc/systemd/system/etcd.service"

- hosts: lb
  tasks:
  - name: stop keepalived service
    shell: systemctl disable keepalived && systemctl stop keepalived
    ignore_errors: true

  - name: stop haproxy service
    shell: systemctl disable haproxy && systemctl stop haproxy
    ignore_errors: true

  - name: 清理LB 配置文件目录
    file: name={{ item }} state=absent
    with_items:
    - "/etc/haproxy"
    - "/etc/keepalived"
    ignore_errors: true
