- name: gen-master-cert
  shell: "{{ bin_dir }}/cfssl gencert -ca={{ ca_dir }}/ca.pem \
        -ca-key={{ ca_dir }}/ca-key.pem \
        -config={{ ca_dir }}/ca-config.json \
        -profile=kubernetes {{ ca_dir }}/kubernetes-csr.json | {{ bin_dir }}/cfssljson -bare kubernetes"

- name: install-master-cert
  shell: "mv kubernetes.csr kubernetes-key.pem kubernetes.pem {{ ca_dir }}"
