- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - /root/.kube
  - /etc/docker

- name: 集群hosts文件更新
  template: src=hosts.j2 dest=/etc/hosts

- name: 更新环境变量$PATH
  shell: "export PATH=/root/local/bin:$PATH"

- name: 写入环境变量$PATH 
  template: src=profile.j2 dest=/root/.profile

- name: 下载证书工具 CFSSL
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: 准备CA配置文件
  template: src=ca-config.json.j2 dest={{ ca_dir }}/ca-config.json

- name: 准备CA签名请求
  template: src=ca-csr.json.j2 dest={{ ca_dir }}/ca-csr.json

- name: 生成 CA 证书和私钥
  shell: "cd {{ ca_dir }} && cfssl gencert -initca ca-csr.json | cfssljson -bare ca" 
