# harbor 为docker的本地私有镜像仓库
- name: harbor证书目录创建
  file: name=/etc/docker/certs.d/{{ HARBOR_SERVER }} state=directory

# 需要先把harbor服务器证书复制到roles/harbor/files/harbor-ca.crt
- name: harbor服务器证书安装
  copy: src=harbor-ca.crt dest=/etc/docker/certs.d/{{ HARBOR_SERVER }}/ca.crt

