- name: 下载 kube-master 二进制
  copy: src={{ base_dir }}/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl
  - kube-proxy
  - kubelet

- name: 创建 kubernetes 证书签名请求
  template: src=kubernetes-csr.json.j2 dest={{ ca_dir }}/kubernetes-csr.json
  notify:
    - gen-master-cert
    - install-master-cert

- name: 创建 token.csv
  template: src=token.csv.j2 dest=/etc/kubernetes/token.csv

- name: 创建kube-apiserver的systemd unit文件
  template: src=kube-apiserver.service.j2 dest=/etc/systemd/system/kube-apiserver.service
  notify:
    - daemon-reload
    - enable-kube-apiserver

- name: 创建kube-controller-manager的systemd unit文件
  template: src=kube-controller-manager.service.j2 dest=/etc/systemd/system/kube-controller-manager.service
  notify:
    - daemon-reload
    - enable-kube-controller-manager

- name: 创建kube-scheduler的systemd unit文件
  template: src=kube-scheduler.service.j2 dest=/etc/systemd/system/kube-scheduler.service
  notify:
    - daemon-reload
    - enable-kube-scheduler

- name: start-kube-apiserver
  shell: systemctl restart kube-apiserver

- name: start-kube-controller-manager
  shell: systemctl restart kube-controller-manager

- name: start-kube-scheduler
  shell: systemctl restart kube-scheduler
